version: "3.1"

services:
  db:
    container_name: database
    image: sameersbn/postgresql:10-2
    env_file:
      - ".env"
    environment:
      PG_USER: $PG_USER
      PG_PASSWORD: $PG_PASSWORD
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  tgbot:
    container_name: bot
    build:
      context: .
    command: python bot.py
    networks:
      - botnet
    restart: always
    env_file:
      - ".env"
    depends_on:
      - db

networks:
  botnet:
    driver: bridge
