from .mainStates import StudentsRegister
from .mainStates import TeacherRegister
from .mainStates import SendWork
from .mainStates import GetWork
from .mainStates import Advert
from .mainStates import TellWork
from .mainStates import StudentsState
from .mainStates import StudentsUpdates
from .mainStates import TeachersUpdates
